### ISSUE TITLE
Message: chrome not reachable

### ISSUE THREAD

**Issue by toncek87** [philippe2803/twitter-analytics-wrapper#5]
I use remote Debian server... if i run reports = ReportDownloader(xxxx), there is error..

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.5/site-packages/twitter_analytics/downloader.py", line 67, in __init__
    self.browser = webdriver.Chrome("/usr/lib/chromium/chromedriver", chrome_options=chrome_options)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.27 (undefined),platform=Linux 3.2.0-4-amd64 x86_64)`

Any tips?

**Comment by philippe2803** [comment]
Could you sort your problem? 
This could be fixed if adding a path argument in the reportsDownloaded for your Chromedriver (not the case at the moment).
